# Swipe left (fingers move left) = go to next workspace
gesture swipe left 3 xdotool key super+shift+Right

# Swipe right (fingers move right) = go to previous workspace
gesture swipe right 3 xdotool key super+shift+Left
