# listen for gestures from any touchpad/device
device all

# swipe left (fingers move left) = go to next workspace
gesture swipe left 3 xdotool key super+shift+Right

# swipe right (fingers move right) = go to previous workspace
gesture swipe right 3 xdotool key super+shift+Left
