##
## === RELOAD
##

alias reload_bash="source $HOME/.bashrc && echo 'Reloaded: ~/.bashrc'"

##
## === HELPERS
##

source_if_present() {
    [[ -f "$1" ]] && source "$1"
}

##
## === SOURCED CONFIG
##

source_if_present "$HOME/.bash_options"
source_if_present "$HOME/.bash_prompt"
source_if_present "$HOME/.shell_aliases"
source_if_present "$HOME/.shell_functions"
source_if_present "$HOME/.shell_options"
source_if_present "$HOME/.shell_paths"
source_if_present "$HOME/.project_aliases"

## .
