shell = "zsh"

platforms = [
  "linux",
  "arch",
  "x11",
  "xfce",
  "lightdm",
]

editors = [
  "zed",
]

tools = [
  "ghostty",
  "tmux",
  "yazi",
]

extras = [
  "lightdm-locale.xprofile",
  "mouse-workspace-buttons.xbindkeysrc",
  "touchpad-workspace-gestures.conf",
]
