## reload
alias reload_zsh="source $HOME/.zshrc && echo 'Reloaded .zshrc!'"

## source file only if it exists
source_if_present() {
  [[ -f "$1" ]] && source "$1"
}

## source modular components if present
source_if_present "$HOME/.zsh_options"
source_if_present "$HOME/.zsh_prompt"

## source shared utils if present
source_if_present "$HOME/.shell_options"
source_if_present "$HOME/.shell_aliases"
source_if_present "$HOME/.shell_functions"
source_if_present "$HOME/.shell_paths"

## initialize completion
autoload -Uz compinit && compinit

## .